/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLayoutRouteRouteImport } from './routes/admin/_layout/route'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutProfileRouteImport } from './routes/admin/_layout/profile'
import { Route as AdminLayoutProjectsRouteImport } from './routes/admin/_layout/projects'
import { Route as AdminLayoutResumeRouteImport } from './routes/admin/_layout/resume'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRouteRoute = AdminLayoutRouteRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)
const AdminLayoutProfileRoute = AdminLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)
const AdminLayoutProjectsRoute = AdminLayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)
const AdminLayoutResumeRoute = AdminLayoutResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/admin/projects': typeof AdminLayoutProjectsRoute
  '/admin/resume': typeof AdminLayoutResumeRoute
  '/admin/': typeof AdminLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/admin/projects': typeof AdminLayoutProjectsRoute
  '/admin/resume': typeof AdminLayoutResumeRoute
  '/admin': typeof AdminLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_layout/profile': typeof AdminLayoutProfileRoute
  '/admin/_layout/projects': typeof AdminLayoutProjectsRoute
  '/admin/_layout/resume': typeof AdminLayoutResumeRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/resume'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/resume'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/admin/login'
    | '/admin/_layout/profile'
    | '/admin/_layout/projects'
    | '/admin/_layout/resume'
    | '/admin/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRouteRoute: typeof AdminLayoutRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/profile': {
      id: '/admin/_layout/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminLayoutProfileRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/projects': {
      id: '/admin/_layout/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminLayoutProjectsRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/resume': {
      id: '/admin/_layout/resume'
      path: '/resume'
      fullPath: '/admin/resume'
      preLoaderRoute: typeof AdminLayoutResumeRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
  }
}

interface AdminLayoutRouteRouteChildren {
  AdminLayoutProfileRoute: typeof AdminLayoutProfileRoute
  AdminLayoutProjectsRoute: typeof AdminLayoutProjectsRoute
  AdminLayoutResumeRoute: typeof AdminLayoutResumeRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteRouteChildren: AdminLayoutRouteRouteChildren = {
  AdminLayoutProfileRoute: AdminLayoutProfileRoute,
  AdminLayoutProjectsRoute: AdminLayoutProjectsRoute,
  AdminLayoutResumeRoute: AdminLayoutResumeRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteRouteWithChildren =
  AdminLayoutRouteRoute._addFileChildren(AdminLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRouteRoute: AdminLayoutRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
